(package "psalm"
         "0.6.0"
         "Interface to Psalm")

(website-url "https://github.com/emacs-php/psalm.el")
(keywords "tools" "php")

(package-file "psalm.el")
(files "*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "php-mode" "1.22.3")
(depends-on "flycheck")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
